-- Postgres/Supabase Migration for Lead Reminders
CREATE TABLE IF NOT EXISTS public.lead_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id UUID NOT NULL, 
  user_id UUID NOT NULL,
  remind_at TIMESTAMP WITH TIME ZONE NOT NULL,
  note TEXT NOT NULL,
  is_processed BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Foreign Keys
ALTER TABLE public.lead_reminders
  ADD CONSTRAINT fk_lead_reminders_lead FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE;

ALTER TABLE public.lead_reminders
  ADD CONSTRAINT fk_lead_reminders_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_lead_reminders_lead_id ON public.lead_reminders(lead_id);
CREATE INDEX IF NOT EXISTS idx_lead_reminders_user_id ON public.lead_reminders(user_id);
CREATE INDEX IF NOT EXISTS idx_lead_reminders_process ON public.lead_reminders(is_processed, remind_at);

-- Row Level Security
ALTER TABLE public.lead_reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see their own reminders" 
  ON public.lead_reminders 
  FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own reminders" 
  ON public.lead_reminders 
  FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reminders" 
  ON public.lead_reminders 
  FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reminders" 
  ON public.lead_reminders 
  FOR DELETE 
  USING (auth.uid() = user_id);
