// Fallback for using MaterialIcons on Android and web.

import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

/**
 * Add your SF Symbols to Material Icons mappings here.
 * - see Material Icons in the [Icons Directory](https://icons.expo.fyi).
 * - see SF Symbols in the [SF Symbols](https://developer.apple.com/sf-symbols/) app.
 */
const MAPPING = {
  "house.fill": "home",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "person.2.fill": "people",
  "briefcase.fill": "business-center",
  "chart.bar.fill": "bar-chart",
  "ticket.fill": "confirmation-number",
  "doc.text.fill": "description",
  "envelope.fill": "email",
  "gear": "settings",
  "plus.circle.fill": "add-circle",
  "magnifyingglass": "search",
  "phone.fill": "phone",
  "calendar": "event",
  "cube.box.fill": "inventory",
  "xmark.circle.fill": "cancel",
  "trash.fill": "delete",
  "trash": "delete",
  "sun.max.fill": "wb-sunny",
  "moon.fill": "nightlight-round",
  "arrow.down.doc.fill": "download",
  "creditcard.fill": "credit-card",
  "arrow.up.arrow.down": "swap-vert",
  "wave.3.right": "contactless",
  "wave.3.right.circle.fill": "contactless",
  "questionmark.circle": "help-outline",
  "square.and.arrow.up": "ios-share",
  "iphone": "smartphone",
  "xmark": "close",
  "checkmark": "check",
  "bell.fill": "notifications",
  "bell.slash.fill": "notifications-off",
  "folder.fill": "folder",
  "person.crop.rectangle.fill": "contact-page",
  "person.fill.badge.plus": "person-add",
  "plus": "add",
  "book.fill": "menu-book",
  "pencil": "edit",
  "globe": "language",
  "mappin.circle.fill": "place",
  "banknote": "payments",
  "ticket": "confirmation-number",
  "checkmark.shield.fill": "verified-user",
  "percent": "percent",
  "chart.pie.fill": "pie-chart",
  "cart.fill": "shopping-cart",
  "cart": "shopping-cart",
  "shield.fill": "shield",
  "car.fill": "directions-car",
  "airplane": "flight",
  "megaphone.fill": "campaign",
  "wrench.and.screwdriver.fill": "build",
  "ellipsis.circle.fill": "more-horiz",
  "shippingbox.fill": "inventory-2",
  "desktopcomputer": "computer",
  "building.2.fill": "business",
  "doc.on.doc.fill": "content-copy",
  "lock.fill": "lock",
  "chevron.down": "expand-more",
  "dollarsign.circle.fill": "monetization-on",
  "eye.fill": "visibility",
  "link": "link",
  "checklist": "checklist",
  "pin.fill": "push-pin",
  "clock": "schedule",
  "clock.fill": "schedule",
  "arrow.triangle.2.circlepath": "sync",
  "checkmark.circle.fill": "check-circle",
  "arrow.clockwise": "refresh",
  "arrow.up.right": "open-in-new",
  "exclamationmark.triangle.fill": "warning",
  "exclamationmark.triangle": "warning",
  "exclamationmark.circle.fill": "error",
  "xmark.octagon.fill": "block",
  "flag.fill": "flag",
  "envelope.open.fill": "drafts",
  "note.text": "sticky-note-2",
  "play.fill": "play-arrow",
  "pause.fill": "pause",
  "doc.text": "description",
  "eye": "visibility",
  "banknote.fill": "payments",
  "person.fill": "person",
  "person.badge.plus.fill": "person-add",
  "cursorarrow.click": "ads-click",
  "arrow.turn.up.left": "keyboard-return",
  "gearshape": "settings",
  "gearshape.fill": "settings",
  "key.fill": "vpn-key",
  "puzzlepiece.fill": "extension",
  "info.circle.fill": "info",
  "lightbulb.fill": "lightbulb",
  "textformat.size": "text-fields",
  "bold": "format-bold",
  "italic": "format-italic",
  "underline": "format-underlined",
  "list.bullet": "format-list-bulleted",
  "list.number": "format-list-numbered",
  "photo.fill": "image",
  "bolt.fill": "bolt",
  "leaf.fill": "eco",
  "square.grid.2x2.fill": "grid-view",
  "camera.fill": "photo-camera",
  "paintbrush.fill": "brush",
  "flame.fill": "local-fire-department",
  "heart.fill": "favorite",
  "list.bullet.rectangle": "view-list",
  "mountain.fill": "landscape",
  "arrow.up.right.circle.fill": "trending-up",
  "chart.line.uptrend.xyaxis": "show-chart",
  "calendar.badge.clock": "event-note",
  "calendar.badge.plus": "event-available",
  "shareplay": "share",
  "printer.fill": "print",
  "newspaper.fill": "article",
  "map.fill": "map",
  "star.fill": "star",
  "person.3.fill": "groups",
  "mic.fill": "mic",
  "video.fill": "videocam",
  "wrench.fill": "build",
  "link.badge.plus": "add-link",
  "chart.bar.xaxis": "bar-chart",
  "checkmark.circle": "check-circle-outline",
  "chevron.up": "expand-less",
  "person.crop.circle.badge.plus": "person-add",
  "person.crop.circle.badge.exclamationmark": "manage-accounts",
  "magnifyingglass.circle.fill": "manage-search",
  "wifi": "wifi",
  "wifi.slash": "wifi-off",
  "number": "numbers",
  "building.columns.fill": "account-balance",
  "tshirt.fill": "checkroom",
  "cross.case.fill": "medical-services",
  "arrow.down": "arrow-downward",
  "arrow.down.circle.fill": "arrow-circle-down",
  "arrow.right": "arrow-forward",
  "arrow.right.circle.fill": "arrow-circle-right",
  "arrow.triangle.merge": "merge-type",
  "arrow.up": "arrow-upward",
  "arrow.up.circle.fill": "arrow-circle-up",
  "arrow.up.doc.fill": "upload-file",
  "bell.badge.fill": "notifications-active",
  "chart.bar": "bar-chart",
  "chart.bar.doc.horizontal.fill": "assessment",
  "checkmark.seal.fill": "verified",
  "clock.arrow.circlepath": "history",
  "clock.badge.exclamationmark": "alarm",
  "doc.badge.clock.fill": "pending-actions",
  "doc.badge.plus": "note-add",
  "doc.fill": "insert-drive-file",
  "folder.badge.plus": "create-new-folder",
  "folder.fill.badge.plus": "create-new-folder",
  "hand.wave.fill": "waving-hand",
  "info.circle": "info-outline",
  "link.circle": "link",
  "paperclip": "attach-file",
  "person.2.wave.2.fill": "connect-without-contact",
  "plus.forwardslash.minus": "exposure",
  "sparkles": "auto-awesome",
  "square.and.arrow.down": "download",
  "square.on.square": "content-copy",
  "tag.fill": "label",
  "textformat.abc": "spellcheck",
  "tray.and.arrow.down.fill": "move-to-inbox",
  "tray.fill": "inbox",
  "wallet.pass.fill": "wallet",
  "zzz": "bedtime",
} as any as IconMapping;

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 * This ensures a consistent look across platforms, and optimal resource usage.
 * Icon `name`s are based on SF Symbols and require manual mapping to Material Icons.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
